#!/bin/sh

CLASSPATH+=":$IPL_HOME/lib/*"
CLASSPATH+=":`dirname $0`/target/structure-0.1-jar-with-dependencies.jar"
export CLASSPATH

java                                                  \
  -ea                                                 \
  -Xmx3g                                              \
  -Dibis.constellation.outputfile=/dev/null           \
  -Dibis.properties.file=`dirname $0`/ibis.properties \
  -Dibis.pool.name=ami650-$RANDOM                     \
  $*
