#!/bin/sh

CLASSPATH+=":$IPL_HOME/lib/*"
CLASSPATH+=":`dirname $0`/target/structure-0.1-jar-with-dependencies.jar"
export CLASSPATH

location=`dirname $0`
pool=ami650-$RANDOM

exec java                                             \
  -ea                                                 \
  -Xmx3g                                              \
  -Dibis.constellation.outputfile=/dev/null           \
  -Dibis.properties.file=$location/ibis.properties    \
  -Dibis.pool.name=$pool                              \
  $*
