#!/bin/sh

DIR=`dirname $0`
CLASSPATH=":$DIR/target/structure-0.2-jar-with-dependencies.jar:$CLASSPATH"

exec java                                             \
  -ea                                                 \
  -server                                             \
  -Xmx3g                                              \
  -cp $CLASSPATH                                      \
  -Dibis.properties.file=$location/ibis.properties    \
  -Dibis.constellation.impl=multithreaded             \
  ibis.structure.Structure $*

