#!/bin/sh

cwd=`cd \`dirname $0\`; pwd`

export STRUCTURE_LOCATION=`cd $cwd/..; pwd`
export STRUCTURE_TMPDIR=$cwd/tmp
export SOLVER=run-structure              # run-structure or run-sat4j
export SOLVER_IMPL=dist                  # dist or mt (only for structure)
export SOLVER_PROCS=1                    # number of machines (1 for sat4j and mt)
export SOLVER_THREADS=1                  # number of threads (1 for sat4j)

prun -np $SOLVER_PROCS -1 $cwd/$SOLVER $*
