#!/bin/sh
# A script to evaluate tests.
#
# Returns 0 on success, 1 on failure
# On success prints the time required to run the test

exec prun -asocial -t 01:00:00 -1 -np $SOLVER_PROCS      \
    $STRUCTURE_LOCATION/bin/time                         \
    $STRUCTURE_LOCATION/bin/$SOLVER $*
