#!/bin/sh

STRUCTURE_LOCATION=~/workspace/structure

java -ea                                                                      \
    -Dibis.cohort.impl=$SOLVER_IMPL                                           \
    -Dibis.cohort.workers=$SOLVER_THREADS                                     \
    -Dlog4j.configuration=file://$STRUCTURE_LOCATION/log4j.properties         \
    -Dibis.properties.file=$STRUCTURE_LOCATION/ibis.properties                \
    ibis.structure.CohortLauncher $*

