#!/bin/sh
# A script to evaluate tests.
#
# Returns 0 on success, 1 on failure
# On success prints the time required to run the test

cwd=`(cd \`dirname $0\`; pwd)`

exec prun -asocial -t 01:00:00 -1 -np $SOLVER_PROCS      \
    $cwd/time $cwd/$SOLVER $*
