#!/bin/sh

date=`date +%F.%T`
stdout=`TMPDIR=$STRUCTURE_TMPDIR mktemp -p. structure.$date.stdout.XXXXXX`
stderr=`TMPDIR=$STRUCTURE_TMPDIR mktemp -p. structure.$date.stderr.XXXXXX`

start=`date +%s%N`
$* > $stdout 2> $stderr
returncode=$?
finish=`date +%s%N`

printf "scale=3\n($finish - $start) / 1000000000\n" | bc -l
echo $stdout
echo $stderr

exit $returncode
