#!/bin/sh
# Works only on das4
# Usage: prun-schedule timeout list program...

PARALLEL=24

timeout=$1
list=$2
shift 2

cat $list | xargs -P$PARALLEL -I'{}' prun -q all.q -1 -np 1 ./run $timeout {} $*
